### ISSUE TITLE
Next - Standalone - Universal Provider - ethers/viem

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal-examples#1]
Hi, I see there's no discussion channel so I'm posting here.

I have a simple prototype of use for Next.js, Walletconnect Standalone, Universal-Provider and ethers.js. Could I collab on adding it? I can simplify this proto and make it more clean (it also needs updating). I could also change ethers for viem or not, both would work.

https://github.com/glitch-txs/walletconnect-standalone-ethers-integration/blob/main/pages/index.tsx

**Comment by 0xAsimetriq** [comment]
For etheres/viem, is there a reason you chose not to use `@walletconnect/ethereum-provider`? You can add that + standalone modal and pass it as provider to ethers or viem.

Example above is something we have planned ^ once few bits get added to ethereum-provider, mainly ability to pass in modal options

**Comment by 0xAsimetriq** [comment]
`Universal Provider` - Kind of a raw provider for wallet connect, for literary any chain
`Ethereum Provider` - Is an [eip-1193](https://eips.ethereum.org/EIPS/eip-1193) compliant provider that wraps Universal Provider + Has optional settings to incorporate standalone modal. Since it is 1193 compliant (like any other provider i.e. metamask, json rpc etc...) you can pass it to libraries like viem and ethers easily.

As of now, you'll only want to use universal provider if you are working on a non-evm chain or combination of evm and other chains.

**Comment by glitch-txs** [comment]
Hi @0xAsimetriq what do you think about this approach? And adding to pages folder:

```
pages
         l__ index.jsx
         l__ viem.jsx
         l__ ethers.jsx
```

- Also for some reason I'm getting this error after connecting, what's weird is that the same config works fine on my other repo, and despite the error everything works as intended. [This is the repo](https://github.com/glitch-txs/web3modal-examples/blob/main/nextjs-standalone-provider/pages/index.jsx)
![imagen](https://user-images.githubusercontent.com/66949816/226912241-1c955423-0a32-4e55-a521-53e49267211f.png)

- There's a function very useful on Universal-Provider too, that's not found on ethereum-provider, as these libraries (ethers, viem, web3, etc) don't have this functionality of adding the chain id when making a request to a smart contract a work around I was using was the `setDefaultChain` function. [Take a look at this issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/1871#issuecomment-1386647038). This allows me to switch networks when the user is connected to multiple at once.

- On init function, chains need to be set as number but on namespaces as string, do you think it would be easy to be able to set them the same way?

For this two later ones I can open an issue on monorepo if needed.
