### ISSUE TITLE
Metamask on html-ethereum-provider as provide option?

### ISSUE THREAD

**Issue by re2005** [WalletConnect/web3modal-examples#12]
Thanks for the examples they all work pretty well.

I'm trying to make the example [html-ethereum-provider](https://github.com/WalletConnect/web3modal-examples/tree/main/html-ethereum-provider) to also how `Metamask` option to connect and can't manage to make it work.

As on the other examples, `Metamask` is shown as option to connect.

<img width="313" alt="Screenshot 2023-05-31 at 09 29 19" src="https://github.com/WalletConnect/web3modal-examples/assets/2920357/5fb6b341-0ef9-4da2-95a1-2d70c8886abe">

But also using the `QRCode` on the `Metamask` mobile app won't work.

Any ideas on how to achieve that ?
Thanks!

**Comment by glitch-txs** [comment]
hey! this are two different things:

1. MetaMask doesn't work when scanning the QR code because they currently don't support WalletConnect v2, but they will soon.

2. Standalone doesn't show browser wallets in the modal, you need to use web3modal for it. Web3modal uses wagmi's connectors to display this browser wallets.

**Comment by re2005** [comment]
Hi @glitch-txs thanks for the explanation. Indeed I'm used to the V1 where `Metamask` can scan the `QR` and connect.

The other downsdte is that `Wagmi` is based on `React` and in my case I'm contributing with a `VUE` wallet connect `https://github.com/vu3th/vue-dapp` 

What makes me thing that the connector modal perhaps could be Framework\Lib agnostic not depending on `Wagmi`

But perhaps is already like that and I need to update something on my end.

Thanks!

**Comment by glitch-txs** [comment]
Standalone only supports v2, you can only use v1/v2 with web3modal

Also there's an html version which uses the core library of wagmi which doesn't require React and it's compatible with Vue

https://docs.walletconnect.com/2.0/web/web3modal/html/wagmi/installation

**Comment by PaperMold** [comment]
@glitch-txs 
> hey! these are two different things:
> 
>     1. MetaMask doesn't work when scanning the QR code because they currently don't support WalletConnect v2, but they will soon.
> 
>     2. Standalone doesn't show browser wallets in the modal, you need to use web3modal for it. Web3modal uses wagmi's connectors to display this browser wallets.

Hey there! If standalone doesn't show browser wallets and web3modal doesn't work with EthereumProvider, what's the alternative to connect any of this modals with ethers v6 and have browser and mobile wallets?

EDIT: Actually coinbase wallet (fd20dc426fb37566d803205b19bbc1d4096b248ac04548e3cfb6b3a38bd033aa) works in browser.
But metamask (c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96) shows QR code.
Is there a way to make browser metamask work with this modal?
