### ISSUE TITLE
auth-html

### ISSUE THREAD

**Issue by PrinceMuteh** [WalletConnect/web3modal-examples#14]
solve module specifier "@web3modal/auth-html". Relative references must start with either "/", "./", or "../".

i usually get this error when i run the project without npm run dev.. is there a way to run the project without npm run dev everytime

**Comment by glitch-txs** [comment]
Not at the moment, but they're developing a cdn for this.

**Comment by houdindahouse** [comment]
![image](https://github.com/WalletConnect/web3modal-examples/assets/125626217/7926833c-20ea-458c-bab3-414e84502de9)
ive encountred the same problem i tried adding the buffer but it didnt work.
Thanks in advance

**Comment by PrinceMuteh** [comment]
![image](https://github.com/WalletConnect/web3modal-examples/assets/46409640/360f4f2a-e35d-4514-8969-368d74660162)


also getting the same error

**Comment by PrinceMuteh** [comment]
> CDN is now available https://docs.walletconnect.com/2.0/web/web3modal/html/auth-api/installation#add-packages-cdn



> CDN is now available https://docs.walletconnect.com/2.0/web/web3modal/html/auth-api/installation#add-packages-cdn

please take at Look at it again... thanks in advance
