### ISSUE TITLE
switchNetwork

### ISSUE THREAD

**Issue by summer233333** [WalletConnect/web3modal-examples#27]
https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-html
Why is the Demo configured with chains that cannot be switched
![image](https://github.com/WalletConnect/web3modal-examples/assets/40909307/e6354d91-75de-4b50-855e-f9e2ad0c56fd)

**Comment by 0xAsimetriq** [comment]
Dapp can configure any chains they want, we chose these 4 for examples.

When connected to wallet, modal shows only chains that were approved by it, in this case looks like only ethereum was approved.

If wallet also approved `wallet_addEthereumChain` method, all chains are available.

What you are seeing (just 1 approved chain) usually happens on wallets who have not fully implemented WalletConnect v2
