### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by mzbanez** [WalletConnect/web3modal-examples#31]
Our project has been using the CDN version 1.7
`<script src="https://cdn.jsdelivr.net/npm/@walletconnect/web3-provider@1.7.1/dist/umd/index.min.js"></script>
`
It's been working fine until the recent 2.0 upgrade!
Now, our project is throwing errors and could connect using wallet connect

Can you guys provide a CDN source for the current version 2?
(The CDN versions:
 walletconnect-modal-auth-html-cdn
 walletconnect-modal-sign-html-cdn
shared on this repository shared is also throwing errors!)

Thanks in advance!

**Comment by 0xAsimetriq** [comment]
@mzbanez What errors are you encountering?

**Comment by khoifuixlabs** [comment]
I tried to use web3modal-wagmi-html-cdn and encountered this error 
<img width="1280" alt="image" src="https://github.com/WalletConnect/web3modal-examples/assets/130330387/d2eedf1b-4661-4c7c-9eb0-39556e9433cc">

The w3m-core-button did not show as well 
<img width="940" alt="image" src="https://github.com/WalletConnect/web3modal-examples/assets/130330387/9970d94f-0724-4f9e-ba15-3b0ba3bf0847">

**Comment by 0xAsimetriq** [comment]
Please see https://github.com/WalletConnect/web3modal/releases/tag/2.7.0 we removed polyfils, so you will need to add missing ones manually.
