### ISSUE TITLE
Help with contracts write

### ISSUE THREAD

**Issue by webnatrix** [WalletConnect/web3modal-examples#34]
Recently added viem, I can't figure out how to call contract on a note using walletconnect and web3model

```
import { 
  getContract,
  writeContract
} from '@wagmi/core';
```
```
const contract = getContract({
  address: "0x78867BbEeF44f2326bF8DDd1941a4439382EF2A7", 
  abi: abi,
  walletClient: ?????
});
```
How to connect it?  I found in the instructions that viem walletconnect2 is not supported,
https://viem.sh/docs/faq.html#why-doesn-t-wallet-client-support-public-actions

**Comment by 0xAsimetriq** [comment]
This is entirely within wagmi scope not modal examples, so will close this issue.
