### ISSUE TITLE
cant waite for web3Modal.connect reponse

### ISSUE THREAD

**Issue by nongyehezuoshe** [WalletConnect/web3modal-examples#35]
for `walletconnect-modal-sign-html-cdn` , cant wait for any respons . [https://github.com/WalletConnect/web3modal-examples/blob/main/walletconnect-modal-sign-html-cdn/main.js#L21C5-L21C5](https://github.com/WalletConnect/web3modal-examples/blob/main/walletconnect-modal-sign-html-cdn/main.js#L21C5-L21C5)

**Comment by 0xAsimetriq** [comment]
@nongyehezuoshe what concrete issue / error are you facing?

**Comment by nongyehezuoshe** [comment]
I believe the `console.info(session);` at this location should output the `session` after a successful connection, but I haven't been able to see any output from it.
