### ISSUE TITLE
cdn examples not working

### ISSUE THREAD

**Issue by shazow** [WalletConnect/web3modal-examples#38]
Hi there,

I'm having trouble making them work locally. For example: `web3modal-wagmi-html-cdn` just shows up blank. I can see the resources successfully loaded, and I don't think there are any relevant console errors (screenshot below), but the page remains blank. This is using a fresh clone with `npx http-server` as instructed.

Similarly with other examples, there's the hard-coded button but it doesn't do anything.

Is there a working live deployed version of these examples anywhere? (Maybe setup a Github Pages for them?)

![image](https://github.com/WalletConnect/web3modal-examples/assets/6292/1e166d83-c291-4dfb-9f3b-cba0a5de7d37)

**Comment by shazow** [comment]
Reverting to an earlier version (e.g. 2.5.0) seems to work. Looks like it might be a 2.7.x issue?

**Comment by glitch-txs** [comment]
You'll need to add some pollyfills, please follow https://github.com/WalletConnect/web3modal/issues/1192 instructions

**Comment by shazow** [comment]
I presume you'll need to add them to your examples to make them functional again too. :)

**Comment by glitch-txs** [comment]
thoughts? @0xAsimetriq 👀

**Comment by FiveNine** [comment]
I was encountering the same issue except couldn't get it to work even on v2.5.0.
I have also tried adding the "pollyfills" as suggested in `main.js` with no difference.
I was trying out the `walletconnect-modal-auth-html-cdn` example.
It'd be awesome if we could get some working examples for these in the repo. 👀
