### ISSUE TITLE
Hosted example

### ISSUE THREAD

**Issue by fulldecent** [WalletConnect/web3modal-examples#40]
For this example https://github.com/WalletConnect/web3modal-examples/tree/main/web3modal-wagmi-html

please host it somewhere.

This will allow me to access it with one click instead of (as currently) a hundred clicks.

**Comment by glitch-txs** [comment]
hosting web3modal-examples is not planned at the moment.

**Comment by fulldecent** [comment]
To be clear, we're talking about just turning in GitHub Pages. Not in scope?

**Comment by glitch-txs** [comment]
Not for v2 at least. And we don't have CDN for v3 atm unfortunately
