### ISSUE TITLE
missing typescript example

### ISSUE THREAD

**Issue by ghost** [WalletConnect/web3modal-examples#41]
I wanted to play around with web3modal in typescript.

I followed [the official guide](https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/installation), but was unable to finish my setup due to dependency problems

to reproduce run the following:

1. `npx create-react-app web3modal --template typescript`
2. `cd web3modal `
3. `npm install @web3modal/ethereum @web3modal/react wagmi viem`
[initial problem screenshot](https://i.stack.imgur.com/3XKXS.png)

so I tried to solve it:

4. `npm i typescript@^5 (which results in warning shown below)`
[warnings screenshot](https://i.stack.imgur.com/XhH5L.png)

5. `npm install @web3modal/ethereum @web3modal/react wagmi viem`
which results in more errors now, screenshot truncated [more errors screenshot](https://i.stack.imgur.com/aOk86.png)

I tried searching for a version of web3modal that uses typescript ^4, but after going down to 2.3.0 - it still sits at 5.0.4.

so my question is:
is there any react/typescript example that uses up-to-date versions of web3modal? and if not - what are the versions of web3modal/wagmi/viem that I can downgrade to to still use typescript 4.9.5?

first published here: https://stackoverflow.com/questions/76835789/a-working-example-of-web3modal-with-typescript-5

**Comment by glitch-txs** [comment]
try adding `"skipLibCheck": true` in the tsconfig.json file, this is more related to Wagmi https://wagmi.sh/react/typescript

**Comment by ghost** [comment]
`--legacy-peer-deps` that you suggested on SO worked (I didn't try to implement it yet, but at least the installation worked).
just one more question - what's the best way to contact you guys? issues or SO?
I duplicated my question this time, which is annoying for you, so I'd love to avoid it in the future

**Comment by glitch-txs** [comment]
you can tag me on general discussions, thanks! :)
