### ISSUE TITLE
suggested clarification for CDN usage

### ISSUE THREAD

**Issue by xaerial** [WalletConnect/web3modal-examples#46]
the example project wasn't working for me (button not loading), but this code at the start of the main.js helped make it work:

if (typeof process === 'undefined') {
  window.process = {
    env: { NODE_ENV: 'development' }
  };
}

**Comment by chrispongl** [comment]
I just reactived my disabled account in github just to say that you are a f*cking god. I was DAYS trying to fix the code because the CDN was not working. I tried everything possible and wasnt working... just added this code and now is working perfectly. You are a angel, pal.

**Comment by xaerial** [comment]
awesome - happy to hear it!

**Comment by vitoff34** [comment]
You are an absolute legend.

**Comment by olamicreas** [comment]
Still doesn't work for m below is it error

"Uncaught (in promise) ReferenceError: process is not defined
    at hey-listen.es.js:3:5"

**Comment by olamicreas** [comment]
Here is the new error

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Xa (index.es.js:4:12665)
    at zl (index.es.js:27:12199)
    at Gx (index.es.js:27:12114)
    at index.es.js:27:30057
    at Array.forEach (<anonymous>)
    at Mc.createProviders (index.es.js:27:29984)
    at Mc.checkStorage (index.es.js:27:29129)
    at async Mc.initialize (index.es.js:27:29226)
    at async Mc.init (index.es.js:27:26398)

> the example project wasn't working for me (button not loading), but this code at the start of the main.js helped make it work:
> 
> if (typeof process === 'undefined') { window.process = { env: { NODE_ENV: 'development' } }; }
