### ISSUE TITLE
All of the CDN examples are broken

### ISSUE THREAD

**Issue by fulldecent** [WalletConnect/web3modal-examples#48]
I have loaded each of the CDN examples. Here are the errors you get. None of them work.

![Screenshot 2023-09-02 at 18 05 58](https://github.com/WalletConnect/web3modal-examples/assets/382183/89befca7-b56e-4918-ba38-3484936fe010)
![Screenshot 2023-09-02 at 18 05 29](https://github.com/WalletConnect/web3modal-examples/assets/382183/d5016ca5-337d-4f58-b198-a6029a812efd)
![Screenshot 2023-09-02 at 18 05 11](https://github.com/WalletConnect/web3modal-examples/assets/382183/3c57471f-dfb1-411a-86b5-00492a1a1aff)

**Comment by turinglabsorg** [comment]
same issue here

**Comment by anilbx** [comment]
https://github.com/WalletConnect/web3modal-examples/issues/46


its solved the issue

**Comment by fulldecent** [comment]
I see this is closed. 

Can a reference please be made to the commit that fixed this?
