### ISSUE TITLE
There is a 404 error for one of the wallets

### ISSUE THREAD

**Issue by livid** [WalletConnect/web3modal-examples#6]
It seems one of the wallet image is a 404:

https://pbs.twimg.com/profile_images/1566773491764023297/IvmCdGnM_400x400.jpg

<img width="1316" alt="Screenshot 2023-04-28 at 1 45 29 AM" src="https://user-images.githubusercontent.com/11427/235100516-4dbbd37d-34d0-48f0-9dae-b5bf4f7ad493.png">

**Comment by livid** [comment]
It's from here:

https://github.com/WalletConnect/web3modal-examples/blob/main/html/main.js

**Comment by 0xAsimetriq** [comment]
That was for custom image which I guess was removed, examples have been simplified and updated now, so closing this issue.
