### ISSUE TITLE
Next 13.4 App Router and Can't resolve "fs" Error while using wagmi

### ISSUE THREAD

**Issue by berkaycirak** [WalletConnect/web3modal-examples#8]
Hi, I am trying to add web3modal into my Next 13.4 project including App Router but it gives me **fs** error. I Could't handle, do you have any idea? My code is at the bottom
<img width="927" alt="Screenshot 2023-05-12 at 13 59 43" src="https://github.com/WalletConnect/web3modal-examples/assets/81809211/d97b46c2-778b-467f-b0f4-544657e1c6be">

**Here is my next code**

```
"use client";

import { ReactNode, useEffect, useState } from "react";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";
import {
      EthereumClient,
      w3mConnectors,
      w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { arbitrum, mainnet, polygon } from "wagmi/chains";

interface ProvidersProps {
      children: ReactNode;
}

const projectId = "xxxxxxx";

const chains = [mainnet, polygon, arbitrum];

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);

const wagmiConfig = createConfig({
      autoConnect: true,
      connectors: w3mConnectors({ version: 1, chains, projectId }),
      publicClient,
});

// 3. Configure modal ethereum client
const ethereumClient = new EthereumClient(wagmiConfig, chains);
const Providers: React.FC<ProvidersProps> = ({ children }) => {
      const [ready, setReady] = useState(false);

      useEffect(() => {
            setReady(true);
      }, []);

      return (
            <>
                  <Toaster position="top-center" reverseOrder={false} />
                  <ThemeProvider attribute="class">
                        {ready ? (
                              <WagmiConfig config={wagmiConfig}>
                                    {children}
                              </WagmiConfig>
                        ) : null}
                  </ThemeProvider>
                  <Web3Modal
                        projectId={projectId}
                        ethereumClient={ethereumClient}
                  />
            </>
      );
};

export default Providers;
```

**Comment by tolgaisik** [comment]
i had the same error, help appretiated.

**Comment by 0xAsimetriq** [comment]
looks like issue is coming from our legacy client for v1 (which is used by wagmi). Will ping the team, but out of curiosity, do you experience any issues when you set `version: 2`?

**Comment by tolgaisik** [comment]
i have tried. it still not working with version: 2.

**Comment by 0xAsimetriq** [comment]
@tolgaisik which error are you getting there?

**Comment by tolgaisik** [comment]
same fs not found

**Comment by berkaycirak** [comment]
still same, I have updated to v2 but "fs" error is still persisting

**Comment by 0xAsimetriq** [comment]
Just caught up on this, for wagmi / web3modal related functionality, you'll likely want to create a separate clientside component https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive

**Comment by berkaycirak** [comment]
Actually I have a separate clientside component but I couldn't understand. Maybe you can try that by using App router also

**Comment by glitch-txs** [comment]
I think @0xAsimetriq the use client need to be added to the react components of the library? I know some libraries were doing this.

I would also suggest and alternative workaround to `setReady` since this prevents to render the whole app on the server

**Comment by 0xAsimetriq** [comment]
Interesting, we could deff have use client on our end 👌

**Comment by 0xAsimetriq** [comment]
That said, I think there will still be few issues coming from wagmi (under the hood a lot of connectors are probably using libs that are not supporting app dir yet). Any suggestions for this?

**Comment by tolgaisik** [comment]
Thanks for response

**Comment by glitch-txs** [comment]
doesn't web3modal use injected connector only? As far as I know wagmi uses react-query which has already [upgraded to support app dir](https://github.com/TanStack/query/commit/017867eff4d8c5ed536c9c8282ad64884e64eb43) not sure about other deps tbh, I guess wagmi should upgrade too

**Comment by tolgaisik** [comment]
@glitch-txs i am going to keep an eye on wagmis issue list.

**Comment by 0xAsimetriq** [comment]
For time being, wagmi guys have created an example of wagmi and web3modal in nextjs `app` https://github.com/wagmi-dev/create-wagmi/tree/main/templates/next/web3modal/src

We'll likely update our examples to be something similar to this 👍

**Comment by berkaycirak** [comment]
Thanks for answer, it is working now but there is something giving error but it doesn't affect the project. I have also cloned your create-wagmi project with next.js app, there is also same error (can't resolve errors) on the CLI. 
![Screenshot 2023-05-16 at 12 01 56](https://github.com/WalletConnect/web3modal-examples/assets/81809211/171af5b9-87db-4aa8-acac-10d21c305c91)

**Comment by berkaycirak** [comment]
Besides that, in your code you have used useEffect for mounting. Without doing that, it renders the app from the server and sends a pre-rendered html to client. I guess, it is better for SEO and page loading

#Without useEffect 
```
'use client'

import { EthereumClient } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/react'
import * as React from 'react'
import { WagmiConfig } from 'wagmi'

import { chains, config, walletConnectProjectId } from '../wagmi'

const ethereumClient = new EthereumClient(config, chains)

export function Providers({ children }: { children: React.ReactNode }) {

  return (
    <WagmiConfig config={config}>
      {children}
      <Web3Modal
        projectId={walletConnectProjectId}
        ethereumClient={ethereumClient}
      />
    </WagmiConfig>
  )
}
```

**Comment by 0xAsimetriq** [comment]
Ty for more info, will look into loki warning (this is package we use for storage on nodejs side, but it won't be used client side, hence why you can ignore it for now).

As for useEffect, we use it as recommendation from wagmi, I believe you might run into issues without it, plus there is point in rendering this html on the server as all wallet details are only accessible within user browser's localStorage thus need to re-render clientside anyway.

**Comment by berkaycirak** [comment]
Thanks for answers, in that case my whole app will be a blank page at the beginning for both server and client. Isn't it bad for google crawlers (SEO) and page loading time? What do you think

**Comment by berkaycirak** [comment]
Thanks for your answers
